create database healthdatadb;

use healthdatadb;

CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

CREATE TABLE BRONZE.ProviderInfo
(
	CMS_Certification_Number_CCN VARCHAR ,
	Provider_Name VARCHAR ,
	Provider_Address VARCHAR ,
	City_Town VARCHAR ,
	State VARCHAR ,
	ZIP_Code INT ,
	Telephone_Number VARCHAR ,
	Provider_SSA_County_Code INT ,
	County_Parish VARCHAR ,
	Ownership_Type VARCHAR ,
	Number_of_Certified_Beds INT ,
	Average_Number_of_Residents_per_Day DECIMAL,
	Average_Number_of_Residents_per_Day_Footnote VARCHAR,
	Provider_Type VARCHAR,
	Provider_Resides_in_Hospital VARCHAR,
	Legal_Business_Name VARCHAR,
	Date_First_Approved_to_Provide_Medicare_and_Medicaid_Services DATE,
	Affiliated_Entity_Name VARCHAR,
	Affiliated_Entity_ID smallint,
	Continuing_Care_Retirement_Community VARCHAR,
	Special_Focus_Status VARCHAR,
	Abuse_Icon VARCHAR,
	Most_Recent_Health_Inspection_More_Than_2_Years_Ago VARCHAR,
	Provider_Changed_Ownership_in_Last_12_Months VARCHAR,
	With_a_Resident_and_Family_Council VARCHAR,
	Automatic_Sprinkler_Systems_in_All_Required_Areas VARCHAR,
	Overall_Rating DECIMAL,
	Overall_Rating_Footnote INT,
	Health_Inspection_Rating INT,
	Health_Inspection_Rating_Footnote INT,
	QM_Rating INT,
	QM_Rating_Footnote INT,
	Long_Stay_QM_Rating INT,
	Long_Stay_QM_Rating_Footnote INT,
	Short_Stay_QM_Rating INT,
	Short_Stay_QM_Rating_Footnote INT,
	Staffing_Rating INT,
	Staffing_Rating_Footnote INT,
	Reported_Staffing_Footnote INT,
	Physical_Therapist_Staffing_Footnote INT,
	Reported_Nurse_Aide_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Reported_LPN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Reported_RN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Reported_Licensed_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Reported_Total_Nurse_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Total_number_of_nurse_staff_hours_per_resident_per_day_on_the_weekend DECIMAL,
	Registered_Nurse_hours_per_resident_per_day_on_the_weekend DECIMAL,
	Reported_Physical_Therapist_Staffing_Hours_per_Resident_Per_Day DECIMAL,
	Total_nursing_staff_turnover DECIMAL,
	Total_nursing_staff_turnover_footnote INT,
	Registered_Nurse_turnover DECIMAL,
	Registered_Nurse_turnover_footnote INT,
	Number_of_administrators_who_have_left_the_nursing_home INT,
	Administrator_turnover_footnote INT,
	Nursing_Case_Mix_Index DECIMAL,
	Nursing_Case_Mix_Index_Ratio DECIMAL,
	Case_Mix_Nurse_Aide_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Case_Mix_LPN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Case_Mix_RN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Case_Mix_Total_Nurse_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Case_Mix_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Adjusted_Nurse_Aide_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Adjusted_LPN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Adjusted_RN_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Adjusted_Total_Nurse_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Adjusted_Weekend_Total_Nurse_Staffing_Hours_per_Resident_per_Day DECIMAL,
	Rating_Cycle_1_Standard_Survey_Health_Date DATE,
	Rating_Cycle_1_Total_Number_of_Health_Deficiencies INT,
	Rating_Cycle_1_Number_of_Standard_Health_Deficiencies INT,
	Rating_Cycle_1_Number_of_Complaint_Health_Deficiencies INT,
	Rating_Cycle_1_Health_Deficiency_Score smallint,
	Rating_Cycle_1_Number_of_Health_Revisits INT,
	Rating_Cycle_1_Health_Revisit_Score INT,
	Rating_Cycle_1_Total_Health_Score INT,
	Rating_Cycle_2_Standard_Health_Survey_Date DATE,
	Rating_Cycle_2_Total_Number_of_Health_Deficiencies INT,
	Rating_Cycle_2_Number_of_Standard_Health_Deficiencies INT,
	Rating_Cycle_2_Number_of_Complaint_Health_Deficiencies INT,
	Rating_Cycle_2_Health_Deficiency_Score smallint,
	Rating_Cycle_2_Number_of_Health_Revisits INT,
	Rating_Cycle_2_Health_Revisit_Score INT,
	Rating_Cycle_2_Total_Health_Score INT,
	Rating_Cycle_3_Standard_Health_Survey_Date DATE,
	Rating_Cycle_3_Total_Number_of_Health_Deficiencies INT,
	Rating_Cycle_3_Number_of_Standard_Health_Deficiencies INT,
	Rating_Cycle_3_Number_of_Complaint_Health_Deficiencies INT,
	Rating_Cycle_3_Health_Deficiency_Score INT,
	Rating_Cycle_3_Number_of_Health_Revisits INT,
	Rating_Cycle_3_Health_Revisit_Score INT,
	Rating_Cycle_3_Total_Health_Score INT,
	Total_Weighted_Health_Survey_Score DECIMAL,
	Number_of_Facility_Reported_Incidents INT,
	Number_of_Substantiated_Complaints INT,
	Number_of_Citations_from_Infection_Control_Inspections INT,
	Number_of_Fines INT,
	Total_Amount_of_Fines_in_Dollars DECIMAL,
	Number_of_Payment_Denials VARCHAR,
	Total_Number_of_Penalties INT,
	Location VARCHAR,
	Latitude DECIMAL,
	Longitude DECIMAL,
	Geocoding_Footnote INT,
	Processing_Date DATE
); 


CREATE TABLE BRONZE.DailyNurseStaffingBK(
	PROVNUM	VARCHAR,
	PROVNAME VARCHAR,	
	CITY VARCHAR,	
	STATE VARCHAR,	
	COUNTY_NAME VARCHAR,	
	COUNTY_FIPS	VARCHAR,
	CY_Qtr	VARCHAR,
	WorkDate VARCHAR,	
	MDScensus VARCHAR,	
	Hrs_RNDON	DECIMAL,
	Hrs_RNDON_emp	DECIMAL,
	Hrs_RNDON_ctr	DECIMAL,
	Hrs_RNadmin	DECIMAL,
	Hrs_RNadmin_emp	DECIMAL,
	Hrs_RNadmin_ctr	DECIMAL,
	Hrs_RN	DECIMAL,
	Hrs_RN_emp	DECIMAL,
	Hrs_RN_ctr	DECIMAL,
	Hrs_LPNadmin	DECIMAL,
	Hrs_LPNadmin_emp DECIMAL,	
	Hrs_LPNadmin_ctr DECIMAL,	
	Hrs_LPN	DECIMAL,
	Hrs_LPN_emp	DECIMAL,
	Hrs_LPN_ctr	DECIMAL,
	Hrs_CNA	DECIMAL,
	Hrs_CNA_emp	DECIMAL,
	Hrs_CNA_ctr	DECIMAL,
	Hrs_NAtrn	DECIMAL,
	Hrs_NAtrn_emp	DECIMAL,
	Hrs_NAtrn_ctr	DECIMAL,
	Hrs_MedAide	DECIMAL,
	Hrs_MedAide_emp	DECIMAL,
	Hrs_MedAide_ctr DECIMAL
);

CREATE TABLE IF NOT EXISTS bronze.ingested_files (
    filename     VARCHAR(512) PRIMARY KEY,
    table_name   VARCHAR(128) NOT NULL,
    load_time    TIMESTAMP DEFAULT GETDATE()
);