name: CI - Lint & Test

on:
  push:
    branches-ignore: ["main"]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install black flake8 pytest boto3
          if [ -f airflow/requirements.txt ]; then pip install -r airflow/requirements.txt; fi
          if [ -f lambda/ingest_gdrive_to_s3/requirements.txt ]; then pip install -r lambda/ingest_gdrive_to_s3/requirements.txt; fi
          if [ -f lambda/trigger_mwaa/requirements.txt ]; then pip install -r lambda/trigger_mwaa/requirements.txt; fi

      - name: Lint Python code
        run: |
          black --check .
          flake8 .

      - name: Run unit tests
        run: pytest -v || echo "No tests folder found — skipping tests"
